---
title: "Seasons Greetings by Riinu Pius"
author: "Derek Sollberger"
date: "2022-12-22"
format: html
---

a place to collect nerdy holiday plots



```{r}
library("tidyverse")
```

```{r}
# https://gist.github.com/riinuots/52c0089bd5c41a44389e95cc8cb3943d
one = tibble(x    = c(2, 4, 3, 2.75, 2.75, 3.25, 3.25),
             y    = c(1, 1, 6, 0,    1,    1,    0),
            group = c(rep("#005a32", 3), rep("#543005", 4)))
              
ggplot(one, aes(x, y, fill = group)) +
  geom_polygon()
```

```{r}
two = tribble(~x,   ~y,
              2.7,  2,
              3,    3,
              3.4,  1.6,
              3.5,  2.5,
              3.1,  4,
              2.95, 5,
              2.7,  3.7,
              2.4,  2.45,
              2.35, 1.7,
              3.1,  2.1,
              3.2,  3.1,
              2.75, 3,
              2.9, 1.4,
              2.9, 4.4) %>% 
  mutate(group = "gold")

ggplot(one, aes(x, y, fill = group)) +
  geom_polygon() +
  geom_point(data = two, shape = 21, size = 5)
```

