---
title: "Resources about Artificial Intelligence Tools"
author: "Derek Sollberger"
date: "2023-07-31"
format:
  html:
    theme: cerulean
    toc: true

---

(I wanted web space where I can organize various links I have encountered about artificial intelligence tools.

# General

* (2023-06-14) [Are Your Students Ready for AI?](https://hbsp.harvard.edu/inspiring-minds/are-your-students-ready-for-ai) by Oguz A. Acar

# Image Generation

* (2023-08-18) [AI-Created Art Isn’t Copyrightable](https://www.hollywoodreporter.com/business/business-news/ai-works-not-copyrightable-studios-1235570316/) by Winston Cho
* Computerphile

    - (2022-10-20) [Stable Diffusion in Code (AI Image Generation) ](https://www.youtube.com/watch?v=-lz30by8-sU)
    - (2022-10-04) [How AI Image Generators Work (Stable Diffusion / Dall-E)](https://www.youtube.com/watch?v=1CIpzeNxIhU)
    
# News Stories

* (2023-08-29) [How to Use AI to Talk to Whales—and Save Life on Earth](https://www.wired.com/story/use-ai-talk-to-whales-save-life-on-earth/) by Camille Bromley
* (2023-08-23) [How Artificial Intelligence Gave a Paralyzed Woman Her Voice Back](https://www.ucsf.edu/news/2023/08/425986/how-artificial-intelligence-gave-paralyzed-woman-her-voice-back) by Robin Marks and Laura Kurtzman
* (2023-08-13) [These Women Tried to Warn Us About AI](https://www.rollingstone.com/culture/culture-features/women-warnings-ai-danger-risk-before-chatgpt-1234804367/) by Lorena O'Neil
* (2023-08-10) [Supermarket AI meal planner app suggests recipe that would create chlorine gas](https://www.theguardian.com/world/2023/aug/10/pak-n-save-savey-meal-bot-ai-app-malfunction-recipes) by Tess McClure
* (2023-08-02) [AI improves breast cancer detection rate by 20 percent ](https://www.politico.eu/article/ai-improves-breast-cancer-detection-rate-20-percent-swedish-study/) by Ashleigh Furlong
* (2023-07-25) [Adobe Staff Worried Their AI Tech Could Kill The Jobs Of Their Own Customers](https://www.benzinga.com/news/23/07/33368787/adobe-staff-worried-their-ai-tech-could-kill-the-jobs-of-their-own-customers) by Rounak Jain
* (2023-07-21) [An MIT student asked AI to make her headshot more ‘professional.’](https://www.boston.com/news/the-boston-globe/2023/07/21/mit-student-ai-racial-blind-spots/) about Rona Wang's explorations
* (2023-03-07) [Many bioinformatics programming tasks can be automated with ChatGPT](https://arxiv.org/abs/2303.13528)
* (2022-12-15) [Artificial intelligence is transforming our world](https://ourworldindata.org/ai-impact) by Max Roser

# Studying

* (2023-03-02) [How to learn to code FAST using ChatGPT](https://www.youtube.com/watch?v=VznoKyh6AXs) by Tina Huang